### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by boadude** [drdk/dr-css-inliner#7]
Error when execute.

token not found:
''

**Comment by rasmusfl0e** [comment]
So... can you provide any additional information?

What arguments did you use when executing?

**Comment by boadude** [comment]
I Found the solution: in the HTML i must put:

<code></code>

**Comment by rasmusfl0e** [comment]
@boadude Sounds like you're just fixing the symptoms rather than the actual problem...

The script expects your webpage to have one or more <link rel="stylesheet" /> . The first one found is replaced with an insertion token (`<!-- inline CSS insertion token -->` being the default) so it knows where to put the inlined CSS once it's done collecting the needed rules.

If no <link/> is found (and in turn no CSS to inline) no insertion token is added - which triggers the `token not found` error.

So it sounds like your webage doesn't actually have any stylesheet <link/>s in it? You shouldn't have to manually add the token to your webage (it's an more option for when you want the CSS inserted another lace than the first <link/>) - FYI.
